### ISSUE TITLE
image_info_0  为空

### ISSUE THREAD

**Issue by w867066886** [HAWLYQ/Qc-TextCap#3]
m4c_textvqa/dataset.py那里读的image_info_0为空，报错，请问这是什么信息呀，是我特征提取的有问题吗

**Comment by HAWLYQ** [comment]
抱歉readme里遗漏了一些细节，特征文件需要以image_id+'.npy'的形式来命名，并且直接存储N x 2048的特征。

**Comment by w867066886** [comment]
我命名是对的，存储的是14*14*2048的特征，这里是不对的是嘛，非常感谢您耐心的回答

**Comment by w867066886** [comment]
是在 pythia/datasets/captioning/m4c_control_textcaps/dataset.py这里image_info_0为空，我看您在这里debug过

**Comment by HAWLYQ** [comment]
您可以发一下您的详细出错信息吗？

**Comment by w867066886** [comment]
`2021-12-13T20:11:02 ERROR: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/dataset.py", line 206, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/data3/wangbin/Qc-TextCap-master/pythia/datasets/base_dataset.py", line 83, in __getitem__
    sample = self.get_item(idx)
  File "/data3/wangbin/Qc-TextCap-master/pythia/datasets/vqa/vqa2/dataset.py", line 99, in get_item
    return self.load_item(idx)
  File "/data3/wangbin/Qc-TextCap-master/pythia/datasets/captioning/m4c_control_textcaps/dataset.py", line 462, in load_item
    for k in list(current_sample.image_info_0):
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "tools/run.py", line 87, in <module>
/pythia/datasets/vqa/m4c_textvqa/dataset.py features.keys dict_keys(['image_feature_0', 'image_info_0', 'image_feature_1', 'image_info_1'])
    run()
  File "tools/run.py", line 76, in run
    trainer.train()
  File "/data3/wangbin/Qc-TextCap-master/pythia/trainers/base_trainer.py", line 269, in train
    for batch in self.train_loader:
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data3/wangbin/environment/qc/lib/python3.6/site-packages/torch-1.2.0-py3.6-linux-x86_64.egg/torch/utils/data/dataset.py", line 206, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/data3/wangbin/Qc-TextCap-master/pythia/datasets/base_dataset.py", line 83, in __getitem__
    sample = self.get_item(idx)
  File "/data3/wangbin/Qc-TextCap-master/pythia/datasets/vqa/vqa2/dataset.py", line 99, in get_item
    return self.load_item(idx)
  File "/data3/wangbin/Qc-TextCap-master/pythia/datasets/captioning/m4c_control_textcaps/dataset.py", line 462, in load_item
    for k in list(current_sample.image_info_0):
TypeError: 'NoneType' object is not iterable

`
以上是出错信息，我输出了一下这个current_sample.image_info_0，是有key但是没有value对应的是none，真的非常感谢您的耐心解答！

**Comment by HAWLYQ** [comment]
读取特征文件的类具体位于pythia/datasets/feature_readers.py 中的PaddedFasterRCNNFeatureReader，麻烦debug一下这个类中read函数返回的image_info是否有max_features的值

**Comment by w867066886** [comment]
很奇怪，在pythia/datasets/feature_dataset.py 中的COCOFeatureDataset中重复会调用两次feature_readers读取同一个数据，一次可以读到info，因为读不到的那次造成报错，您遇到过这个问题吗

**Comment by w867066886** [comment]
我没有改动您的代码，用的特征是mmf里面的，虽然可能和您的不一致，但是feature的维度和info是一致的，您方便测试一下github中的代码吗 ...

**Comment by HAWLYQ** [comment]
调用两次是正常的，一次是obj的目录，一次是ocr的目录。你调试的时候feature reader会调用到PaddedFasterRCNNFeatureReader这个类吗？这个类中的read函数会把.npy中特征的第一维，也就是N存在image_info['max_features']中，只要这个信息有，应该就不会出现 pythia/datasets/captioning/m4c_control_textcaps/dataset.py中的那个bug。

**Comment by w867066886** [comment]
请问ocr的feature和obj的feature维度分别是多少呀，具体的维度，是不是我维度设置的有问题，这个n是放在yml里的超参吗

**Comment by HAWLYQ** [comment]
输入特征的维度是N*2048，N的bbox的个数，不是固定的，这个不需要设置。请问您调试的时候，feature reader会调用到PaddedFasterRCNNFeatureReader这个类，并且在这个类中的read函数中把特征的第一维，也就是N存在image_info['max_features']中吗？

**Comment by w867066886** [comment]
是我数据组织的有问题，非常感谢您，另外我想请问一下，您是在什么环境下跑的，用了多久时间呀

**Comment by w867066886** [comment]
用的什么显卡，几块显卡，跑了多久时间

**Comment by HAWLYQ** [comment]
当时在ControlTextCaps训练GQAM的时候，用了一块Tesla V100-SXM2-32GB，batch size=50, max_iterations=16000 (即config中已经设置好的参数)，大概训练要11h左右。（不过没有占满32GB）

**Comment by w867066886** [comment]
非常感谢

**Comment by HAWLYQ** [comment]
不客气~
